development:
  sessions:
    default:
      database: fec_crawl_db
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: fec_crawl_db
      hosts:
        - localhost:27017