accessories-jewelry-bracelets:
  - 93
accessories-jewelry-earrings:
  - 91
accessories-jewelry-fine:
  - 97
accessories-jewelry-necklaces:
  - 90
accessories-jewelry-other:
  - 97
accessories-jewelry-personalized:
  - 97
accessories-jewelry-rings:
  - 92
accessories-gloves:
  - 108
accessories-trend-rock-stars:
  - 97
accessories-belts:
  - 109
accessories-hair:
  - 96
hosiery-socks:
  - 116
hosiery-tights:
  - 114
accessories-hats:
  - 103
accessories-home-gifts-books:
  - 157
accessories-home-gifts-dog:
  - 120
accessories-home-gifts-entertaining:
  - 157
accessories-home-gifts-decor:
  - 157
accessories-home-gifts-stationary:
  - 157
accessories-home-gifts-stationery:
  - 157
accessories-home-gifts-towels:
  - 157
accessories-keychains:
  - 112
accessories-scarves-wraps:
  - 105
accessories-umbrellas:
  - 110
accessories-sunglasses-eyewear-aviator:
  - 100
accessories-sunglasses-eyewear-cat-eye:
  - 100
accessories-sunglasses-eyewear-mirrored:
  - 100
accessories-sunglasses-eyewear-oversized:
  - 100
accessories-sunglasses-eyewear-rectangle:
  - 100
accessories-sunglasses-eyewear-round:
  - 100
accessories-sunglasses-eyewear-special-fit:
  - 100
accessories-sunglasses-eyewear-statement:
  - 100
accessories-sunglasses-eyewear-optical:
  - 100
accessories-eyewear-cases:
  - 102
accessories-tech-headphones:
  - 120
accessories-tech-laptop:
  - 118
accessories-tech-other:
  - 120
accessories-tech-phone:
  - 120
accessories-tech-tablet-reader:
  - 120
accessories-travel:
  - 120
accessories-watches:
  - 98
shoes-boots-flat:
  - 71
shoes-boots-heeled:
  - 72
shoes-boots-knee-high:
  - 70
shoes-booties-flat:
  - 76
shoes-booties-heeled:
  - 62
shoes-booties-lace:
  - 67
shoes-pumps-heels:
  - 60
shoes-pumps-heels-open-toe:
  - 60
shoes-pumps-heels-platforms:
  - 60
accessories-designer-boutique:
  - 97
shoes-flats-ballet:
  - 64
shoes-flats-espadrilles:
  - 66
shoes-flats-loafers:
  - 65
shoes-flats-oxfords:
  - 71
shoes-sandals-flat:
  - 58
shoes-sandals-flip-flops:
  - 58
shoes-sandals-high-heeled:
  - 58
shoes-sandals-platforms:
  - 58
shoes-accessories:
  - 120
shoes-wedges:
  - 63
shoes-sneakers:
  - 59
shoes-rain-wear-cold-weather:
  - 76
shoes-top-shoe-trends-city-sandals:
  - 58
shoes-top-shoe-trends-modern-gladiators:
  - 58
shoes-top-shoe-trends-sophisticated-slides:
  - 58
bags-baby:
  - 77
shoes-designer-boutique:
  - 67
bags-black-handbags:
  - 78
bags-backpacks:
  - 84
bags-beach:
  - 85
bags-hobos:
  - 78
bags-clutches:
  - 81
bags-cosmetic-pouches:
  - 118
bags-cross-body:
  - 82
bags-mini:
  - 82
bags-shoulder:
  - 82
bags-satchels:
  - 78
bags-totes:
  - 77
bags-travel:
  - 85
bags-designer-boutique:
  - 85
bags-wallets:
  - 86
clothing-denim-boot-cut-jeans:
  - 20
clothes-denim-boyfriend-jeans:
  - 28
clothing-denim-cropped-jeans:
  - 22
clothes-denim-distressed-jeans:
  - 27
clothing-denim-flare-jeans-wide-leg:
  - 25
clothes-denim-high-waisted-jeans:
  - 28
clothes-denim-maternity-jeans:
  - 314
clothes-denim-skinny-jeans:
  - 26
clothes-denim-straight-leg-jeans:
  - 23
clothing-denim-black-jeans:
  - 28
clothes-denim-dark-rinse-jeans:
  - 28
clothing-denim-grey-jeans:
  - 28
clothes-denim-light-wash-jeans:
  - 28
clothing-denim-white-jeans:
  - 28
clothing-denim-coated-jeans:
  - 28
clothing-denim-colored-jeans:
  - 28
clothing-denim-printed-jeans:
  - 28
clothing-denim-shorts:
  - 18
clothing-denim-jackets:
  - 51
clothes-denim-designer-boutique:
  - 28
clothing-dresses-casual:
  - 144
clothing-dresses-day-night:
  - 145
clothing-dresses-night-out:
  - 145
clothing-dresses-cocktail:
  - 143
clothing-dresses-formal:
  - 145
clothing-dresses-bridal:
  - 135
clothing-dresses-bright:
  - 144
clothing-dresses-black:
  - 149
clothing-dresses-white:
  - 149
dresses-mini:
  - 148
clothes-dresses-knee-length:
  - 148
clothing-dresses-midi:
  - 148
dresses-maxi:
  - 146
clothing-dresses-strapless:
  - 145
clothing-dresses-one-shoulder:
  - 145
clothing-dresses-longsleeve:
  - 144
clothing-lingerie-bras:
  - 125
clothing-lingerie-camisoles:
  - 123
clothing-lingerie-chemises-slips:
  - 122
clothing-lingerie-garters:
  - 131
clothing-lingerie-panties:
  - 121
clothing-lingerie-robes:
  - 128
lingerie-shapewear:
  - 122
clothing-lingerie-sleepwear:
  - 126
clothing-lingerie-teddies:
  - 122
lingerie-accessories:
  - 131
lingerie-designer-boutique:
  - 131
clothing-jumpsuits-rompers:
  - 38
clothing-loungewear:
  - 165
clothing-jackets-coats-blazers:
  - 48
clothing-jackets-coats-denim:
  - 51
clothing-jackets-coats-fashion:
  - 49
jackets-leather:
  - 50
clothing-jackets-coats-pea:
  - 49
clothing-jackets-coats-puffer:
  - 42
clothing-jackets-coats-trench:
  - 43
jackets-designer-boutique:
  - 57
clothing-maternity:
  - 324
skirts-mini:
  - 16
clothing-skirts-knee-length:
  - 15
clothing-skirts-midi:
  - 15
skirts-maxi:
  - 15
clothing-skirts-dress:
  - 15
skirts-pencil:
  - 15
clothing-skirts-denim:
  - 15
skirts-designer-boutique:
  - 15
clothing-suit-separates:
  - 154
clothing-shorts-denim:
  - 18
clothing-shorts-knee-length:
  - 18
clothing-shorts-short:
  - 18
clothes-swimwear-bikinis:
  - 132
clothes-swimwear-cover-ups:
  - 157
clothes-swimwear-one-pieces:
  - 132
clothing-pants-boot-cut-flare:
  - 29
clothing-pants-cropped:
  - 30
clothing-pants-high-waisted:
  - 29
clothing-pants-leather:
  - 29
clothing-pants-leggings:
  - 113
clothing-pants-leggings-maternity:
  - 319
clothing-pants-skinny:
  - 26
clothing-pants-leggings-slouchy:
  - 29
clothing-pants-straight-leg:
  - 29
clothing-pants-sweatpants-yoga:
  - 34
clothing-pants-wide-leg:
  - 33
pants-designer-boutique:
  - 35
clothing-tops-blouses:
  - 10
clothes-tops-button-down-shirts:
  - 10
clothing-tops-night-out:
  - 14
clothing-tops-sweatshirts-hoodies:
  - 8
clothing-tops-tank:
  - 1
clothing-tops-tees-long-sleeve:
  - 3
clothing-tops-tees-short-sleeve:
  - 2
clothing-tops-tunics:
  - 5
clothes-tops-designer-boutique:
  - 14
clothing-kids-baby:
  - 276
clothing-sweaters-knits-cardigans:
  - 7
sweaters-knits-cashmere:
  - 6
clothing-sweaters-cowlneck:
  - 6
clothing-sweaters-knits-crew-scoop-necks:
  - 6
clothing-sweaters-knits-sweater-dresses:
  - 6
clothing-sweaters-knits-turtlenecks:
  - 6
clothing-sweaters-knits-necks:
  - 6
sweaters-knits-designer-boutique:
  - 6
clothing-vests:
  - 13