men/accessories/bags/:
  - 226
men/accessories/belts/:
  - 247
men/accessories/cuffs/:
  - 250
men/accessories/hats/:
  - 240
men/accessories/jewelry/:
  - 230
men/accessories/luggage/:
  - 222
men/accessories/scarves/:
  - 243
men/accessories/small_leather_goods/:
  - 233
men/accessories/sunglasses/:
  - 237
men/accessories/tech_accessoires/:
  - 236
men/accessories/ties/:
  - 249
men/accessories/umbrella/:
  - 232
men/clothing/beachwear/:
  - 260
men/clothing/cashmere/:
  - 173
men/clothing/coats/:
  - 209
men/clothing/jackets/:
  - 210
men/clothing/jeans/:
  - 187
men/clothing/knitwear/:
  - 173
men/clothing/pants/:
  - 194
men/clothing/shirts/:
  - 170
men/clothing/socks/:
  - 246
men/clothing/sportswear/:
  - 271
men/clothing/suits/:
  - 263
men/clothing/t_shirts/:
  - 166
men/clothing/underwear/:
  - 259
men/clothing/vests/:
  - 207
men/shoes/shoes/:
  - 218
men/shoes/sneakers/:
  - 213
women/accessories/belts/:
  - 109
women/accessories/hats/:
  - 103
women/accessories/home/:
  - 331
women/accessories/lifestyle/:
  - 111
women/accessories/scarves/:
  - 105
women/accessories/sunglasses/:
  - 100
women/accessories/umbrellas/:
  - 110
women/accessories/bracelets/:
  - 93
women/accessories/earrings/:
  - 91
women/accessories/hairclips/:
  - 96
women/accessories/keychains/:
  - 112
women/accessories/necklaces/:
  - 90
women/accessories/rings/:
  - 92
women/lingerie/bras/:
  - 124
women/lingerie/briefs/:
  - 121
women/lingerie/camis/:
  - 123
women/lingerie/corsetry/:
  - 122
women/lingerie/garter_belts/:
  - 109
women/lingerie/shapewear/:
  - 122
women/lingerie/sleepwear/:
  - 126
women/lingerie/stockings/:
  - 115
women/lingerie/shop-by-designer/:
  - 131
women/bags/clutches/:
  - 81
women/bags/luggage/:
  - 85
women/bags/shoulder_bags/:
  - 82
women/bags/small_accessories/:
  - 78
women/bags/small_leather_goods/:
  - 85
women/bags/totes/:
  - 77
women/shoes/ankle_boots/:
  - 69
women/shoes/ballerinas/:
  - 64
women/shoes/boots/:
  - 68
women/shoes/flats/:
  - 65
women/shoes/kitten_heels/:
  - 72
women/shoes/pumps/:
  - 60
women/shoes/sandals/:
  - 67
women/shoes/sneakers/:
  - 59
women/shoes/wedges/:
  - 63
women/clothing/beachwear/:
  - 132
women/clothing/cashmere/:
  - 6
women/clothing/coats/:
  - 57
women/clothing/dresses/:
  - 153
women/clothing/gifts/:
  - 141
women/clothing/jackets/:
  - 57
women/clothing/jeans/:
  - 28
women/clothing/knitwear/:
  - 6
women/clothing/pants/:
  - 35
women/clothing/skirts/:
  - 15
women/clothing/sportswear/:
  - 165
women/clothing/t_shirts/:
  - 2
women/clothing/tops/:
  - 14
women/lingerie/bodysuits/:
  - 131