development:
  adapter: mysql2
  database: simpleLife
  username: root
  password:
  host: localhost

tuantm:
  adapter: mysql2
  database: fec
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: fec
  username: zigexn
  password: 0nly0ne
  host: 133.242.247.38
