# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e24604bc6666aa371fb2079c35f47716106f5ec5fd8b7bc4a66fd59bd61ce66066abb6ac605b7f1eac6a1bcce397841ebc562cff1aad83fd179d5349f1bcda7

test:
  secret_key_base: 703060a4aff9beff31955b47ad6586ff0f61da96da5979bf7a41ee6cbacb2ed39b0eb4b3133a35f69e22396b68c1df90cac999db101beddee16b470e89ad8e2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
